run-name: Running on push by @${{ github.actor }}
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mihaimatei/change-files-action-test@main
        with:
          url: 'my-workflow-optimized-url.com'
